title = "Paulo Alves | Psicólogo Clínico"
baseURL = 'https://www.paulorssalves.com.br'
languageCode = 'pt-br'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = false 

  #footer items
  nextprev = false 
  taglist = false 
  showrss = false 
